FROM python:3.9-buster

RUN apt-get update && apt-get -y install \
    libpq-dev

WORKDIR /app
ADD    ./app/requirements.txt    /app/
RUN    pip install -r requirements.txt

ENV PYTHONUNBUFFERED 1

RUN adduser --disabled-password --no-create-home app

USER app
