FROM python:3.9-buster

ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get -y install libpq-dev && \
    pip install --upgrade pip && \
    adduser --disabled-password --no-create-home app

WORKDIR /app
ADD    ./app/requirements.txt    /app/
RUN    pip install -r requirements.txt

USER app